pipeline{
    parameters{
        choice(name: 'terraformAction',choices: ['apply','destroy'],description: 'Choose your terraform action to perform')
    }

    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    agent any

    stages{
        stage('checkout'){
            steps{
                script {
                    dir("iac-repo"){ 
                        git branch: 'main',url:'https://github.com/ManojKRISHNAPPA/Terraform-Zero-Hero-Series-ITkannadigaru.git'
                    }
                }
            }
        }
    
        stage('Plan'){
            steps{
                // Navigate into the checked-out directory and then into the Project-1 subdirectory
                sh 'cd iac-repo/07-Project-01; terraform init' 
                sh 'cd iac-repo/07-Project-01; terraform plan -out tfplan'
                sh 'cd iac-repo/07-Project-01; terraform show -no-color tfplan >> ../tfplan.txt' // Write plan to parent dir for easier access
            }
        }
    
        stage('approval'){
            steps{
                script {
                    // Read the plan file from the workspace root or the checked out directory (using iac-repo/tfplan.txt)
                    def plan = readFile 'iac-repo/tfplan.txt'
                    
       
                    input(
                        message: "Do you want to proceed with terraform action..?",
                        parameters: [
                            text(name: 'planReview', description: 'Can you review your code one more time', defaultValue: plan)
                        ]
                    )
                }
            }
        }
    
        stage('Apply or Destroy'){
            when{
                expression{
                    return params.terraformAction == 'apply' || params.terraformAction == 'destroy'
                }
            }
    
            steps{
                script{
                    if (params.terraformAction == 'apply'){
                     
                        sh "cd iac-repo/07-Project-01; terraform apply -input=false tfplan" 
                    } else if(params.terraformAction == 'destroy'){
                 
                        sh "cd iac-repo/07-Project-01; terraform destroy -auto-approve" 
                    }
                }
            }
        }

        stage('Backup-statefile'){
            steps{
                sh '''
                cd iac-repo/07-Project-01

                aws s3 cp *.tfstate s3://itkannadigaru-terraform-zero-to-hero/VPC-project/
                '''
            }

        }

    } 
}