pipeline {

    agent any

    parameters {
        choice(
            name: 'terraformAction',
            choices: ['apply', 'destroy'],
            description: 'Choose your terraform action'
        )
    }

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ManojKRISHNAPPA/Terraform-Zero-Hero-Series-ITkannadigaru.git'
            }
        }

        stage('Plan') {
            steps {
                sh '''
                    cd 02-s3-bucket
                    terraform init
                    terraform plan -out=tfplan
                    terraform show -no-color tfplan > ../tfplan.txt
                '''
            }
        }

        stage('Approval') {
            steps {
                script {
                    def plan = readFile 'tfplan.txt'

                    input(
                        message: "Do you want to proceed with terraform action?",
                        parameters: [
                            text(
                                name: 'planReview',
                                description: 'Review the Terraform plan before proceeding',
                                defaultValue: plan
                            )
                        ]
                    )
                }
            }
        }

        stage('Apply or Destroy') {
            when {
                expression {
                    return params.terraformAction == 'apply' || params.terraformAction == 'destroy'
                }
            }
            steps {
                script {
                    if (params.terraformAction == 'apply') {
                        sh '''
                            cd 02-s3-bucket
                            terraform apply -input=false tfplan
                        '''
                    } else {
                        sh '''
                            cd 02-s3-bucket
                            terraform destroy -auto-approve
                        '''
                    }
                }
            }
        }
    }
}
